<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://booklibraryservice.logansrings.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://booklibraryservice.logansrings.com" xmlns:intf="http://booklibraryservice.logansrings.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://booklibraryservice.logansrings.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="main">
    <complexType>
     <sequence>
      <element maxOccurs="unbounded" name="args" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="mainResponse">
    <complexType/>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="mainResponse">

      <wsdl:part element="impl:mainResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="mainRequest">

      <wsdl:part element="impl:main" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="BookLibraryServiceClient">

      <wsdl:operation name="main">

         <wsdl:input message="impl:mainRequest" name="mainRequest">

       </wsdl:input>

         <wsdl:output message="impl:mainResponse" name="mainResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="BookLibraryServiceClientSoapBinding" type="impl:BookLibraryServiceClient">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="main">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="mainRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="mainResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="BookLibraryServiceClientService">

      <wsdl:port binding="impl:BookLibraryServiceClientSoapBinding" name="BookLibraryServiceClient">

         <wsdlsoap:address location="http://localhost:8080/booklibrary/services/BookLibraryServiceClient"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
